name: Test Suite

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  workflow_call:

jobs:
  test_basic:
    runs-on: ubuntu-latest
    name: Recommended
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test deployment tracker
        uses: ./
        with:
          logLevel: DEBUG
          apiHost: ${{ secrets.SHIPBOT_API_HOST }}
          apiKey: ${{ secrets.SHIPBOT_API_KEY }}
          artifactName: my-test-service
          environment: PRODUCTION
          version: 0.0.1
          description: This is a test deployment