name: Test Suite

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  workflow_call:

jobs:
  test_basic:
    runs-on: ubuntu-latest
    name: Recommended
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test deployment tracker
        uses: ./
        with:
          logLevel: DEBUG
          apiHost: ${{ secrets.SHIPBOT_API_HOST }}
          apiKey: ${{ secrets.SHIPBOT_API_KEY }}
          artifactConfig: shipbot.json
          commitSha: 1234567890
          user: ${{ github.actor }}
          environment: PRODUCTION
          version: 0.0.1
          description: This is a test deployment
  test_deployment_multiple_steps:
    runs-on: ubuntu-latest
    name: Multiple Steps Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start deployment
        id: start_deployment
        uses: ./
        with:
          logLevel: DEBUG
          apiHost: ${{ secrets.SHIPBOT_API_HOST }}
          apiKey: ${{ secrets.SHIPBOT_API_KEY }}
          artifactConfig: shipbot.json
          environment: PRODUCTION
          version: 0.0.1
          status: STARTED
          user: ${{ github.actor }}
          commitSha: 1234567890
          description: Starting test deployment

      - name: Simulate deployment work
        id: deployment_work
        run: |
          echo "Simulating deployment work..."
          sleep 5
          # Randomly succeed or fail
          exit $(( RANDOM % 2 ))
        continue-on-error: true

      - name: Mark deployment as succeeded
        if: steps.deployment_work.outcome == 'success'
        uses: ./
        with:
          logLevel: DEBUG
          apiHost: ${{ secrets.SHIPBOT_API_HOST }}
          apiKey: ${{ secrets.SHIPBOT_API_KEY }}
          deploymentId: ${{ steps.start_deployment.outputs.deploymentId }}
          status: SUCCEEDED

      - name: Mark deployment as failed
        if: steps.deployment_work.outcome == 'failure'
        uses: ./
        with:
          logLevel: DEBUG
          apiHost: ${{ secrets.SHIPBOT_API_HOST }}
          apiKey: ${{ secrets.SHIPBOT_API_KEY }}
          deploymentId: ${{ steps.start_deployment.outputs.deploymentId }}
          status: FAILED
